### ISSUE TITLE
sre_constants.error: bogus escape (end of line) when beautifying certain script

### ISSUE THREAD

**Issue by brlin-tw** [hermanbergwerf/bashbeautify#12]
Sample: https://gist.github.com/Lin-Buo-Ren/6370743dae4b4e7e20c2be47d6e93ba7

## Traceback (most recent call last):
```
  File "bashbeautify.py", line 178, in <module>
    main()
  File "bashbeautify.py", line 174, in main
    BeautifyBash().main()
  File "bashbeautify.py", line 169, in main
    error |= self.beautify_file(path)
  File "bashbeautify.py", line 155, in beautify_file
    result,error = self.beautify_string(data,path)
  File "bashbeautify.py", line 75, in beautify_string
    if(re.search(here_string,test_record) and not re.search('<<',test_record)):
  File "/usr/lib/python2.7/re.py", line 146, in search
    return _compile(pattern, flags).search(string)
  File "/usr/lib/python2.7/re.py", line 251, in _compile
    raise error, v # invalid expression
sre_constants.error: bogus escape (end of line)
```

**Comment by brlin-tw** [comment]
The program seems to break after processing this code:

```bash
       # Runtime environment's executable search path priority array
        declare -a RUNTIME_PATH_DIRECTORIES
        IFS=':' \
                read -r -a RUNTIME_PATH_DIRECTORIES <<< "${PATH}"\
                || true # Without this `read` will return 1
```

My hunch is the `<<<` operator...?

**Comment by bergwerf** [comment]
Hmm, I do not actually have much insight into the code unfortunately (it is not mine, but I published it here).
Perhaps @kyeongy has some ideas? He worked on patches before.
